fix jenkins workspace path

diff --git a/java-maven-sonar-argocd-helm-k8s/spring-boot-app/JenkinsFile b/java-maven-sonar-argocd-helm-k8s/spring-boot-app/JenkinsFile
--- a/java-maven-sonar-argocd-helm-k8s/spring-boot-app/JenkinsFile
+++ b/java-maven-sonar-argocd-helm-k8s/spring-boot-app/JenkinsFile
@@ -1,7 +1,7 @@
 pipeline {
 agent any
 
-
+```
 stages {
 
     stage('Build') {
@@ -15,22 +15,30 @@ stages {
     stage('Docker Build') {
         steps {
             dir('java-maven-sonar-argocd-helm-k8s/spring-boot-app') {
-                sh 'docker build -t springboot-app:${BUILD_NUMBER} .'
+                sh "docker build -t springboot-app:${BUILD_NUMBER} ."
             }
         }
     }
 
     stage('Deploy') {
         steps {
-            sh 
-                docker stop springboot-app || true
-                docker rm springboot-app || true
-                docker run -d --name springboot-app -p 8081:8080 springboot-app:${BUILD_NUMBER}
-            
+            sh 'docker stop springboot-app || true'
+            sh 'docker rm springboot-app || true'
+            sh "docker run -d --name springboot-app -p 8081:8080 springboot-app:${BUILD_NUMBER}"
         }
     }
 }
 
+post {
+    success {
+        echo 'Pipeline executed successfully!'
+    }
+
+    failure {
+        echo 'Pipeline failed!'
+    }
+}
+```
 
 }
 
